In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
bene_2008 = pd.read_csv('../data/raw/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv')
bene_2009 = pd.read_csv('../data/raw/DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv')
bene_2010 = pd.read_csv('../data/raw/DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv')
print(bene_2008.head())
print(bene_2009.head())
print(bene_2010.head())

        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             0             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            2
2                       12                        12  ...            2
3                        0                         0  ...            2
4                       12                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0          0.0        0.0        0.0         50.0       10.0        0.0
1          0.0        0.0        0.0          0.0        0.0        0.0
2          0.0        0.0        0.0          0.0        0.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         30.0       40.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0           0.0         0.0         0.0
1         700.0       240.0         0.0
2           0.0         0.0         0.0
3           0.0         0.0         0.0
4         220.0        80.0         0.0

[5 rows x 32 columns]
        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             0             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            1
2                       12                        12  ...            2
3                       12                        12  ...            2
4                       12                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0          0.0        0.0        0.0          0.0        0.0        0.0
1      36000.0     3204.0        0.0         60.0       70.0        0.0
2          0.0        0.0        0.0         30.0       50.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         90.0       40.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0         100.0        20.0         0.0
1        1350.0       530.0       100.0
2          20.0         0.0         0.0
3          90.0        10.0         0.0
4         410.0       140.0         0.0

[5 rows x 32 columns]
        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             Y             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            2
2                       12                        12  ...            2
3                       12                        12  ...            2
4                        9                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0       4000.0     1100.0        0.0          0.0        0.0        0.0
1      16000.0     1100.0        0.0          0.0        0.0        0.0
2          0.0        0.0        0.0          0.0        0.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         40.0        0.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0          90.0        30.0         0.0
1         930.0       150.0         0.0
2           0.0         0.0         0.0
3           0.0         0.0         0.0
4         590.0        60.0         0.0

[5 rows x 32 columns]

In [3]:
print(bene_2008.shape)
print(bene_2009.shape)
print(bene_2010.shape)

(116352, 32)
(114538, 32)
(112754, 32)

In [4]:
#print(bene_2008.columns.tolist())
print(bene_2008['BENE_DEATH_DT'].value_counts(dropna=False))
death_percent = (bene_2008['BENE_DEATH_DT'].notna().sum()/bene_2008.shape[0])*100
print(f"The death percentage in the year 2008 is:{death_percent:.2f}%")

NaN           114538
20080901.0       166
20080101.0       164
20080501.0       158
20081101.0       158
20080301.0       156
20081001.0       155
20081201.0       153
20080701.0       149
20080201.0       142
20080401.0       141
20080801.0       140
20080601.0       132
Name: BENE_DEATH_DT, dtype: int64
The death percentage in the year 2008 is:1.56%

In [5]:
merged_df = pd.merge(bene_2008, bene_2009, on='DESYNPUF_ID')
merged_df = pd.merge(merged_df, bene_2010, on='DESYNPUF_ID')

In [6]:
print(merged_df.shape)

(112754, 94)

In [7]:
# Find IDs present in all three years
ids_2008 = set(bene_2008['DESYNPUF_ID'])
ids_2009 = set(bene_2009['DESYNPUF_ID'])
ids_2010 = set(bene_2010['DESYNPUF_ID'])

common_ids = ids_2008.intersection(ids_2009).intersection(ids_2010)
print(f"Beneficiaries present in all three years: {len(common_ids)}")

Beneficiaries present in all three years: 112754

In [8]:
print(f"The percentage of memebers that survived all three years= {(len(common_ids)/len(bene_2008))*100:.2f} %")

The percentage of memebers that survived all three years= 96.91 %

In [9]:
filtered_bene_2008=bene_2008.loc[bene_2008['DESYNPUF_ID'].isin(common_ids)]
filtered_bene_2009=bene_2009.loc[bene_2009['DESYNPUF_ID'].isin(common_ids)]
filtered_bene_2010=bene_2010.loc[bene_2010['DESYNPUF_ID'].isin(common_ids)]
print(filtered_bene_2008.shape)
print(filtered_bene_2009.shape)
print(filtered_bene_2010.shape)

(112754, 32)
(112754, 32)
(112754, 32)

In [10]:
otp = pd.read_csv('../data/raw/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv', low_memory=False)
print(otp.shape)

(790790, 76)

In [11]:
print(otp.columns.tolist())

['DESYNPUF_ID', 'CLM_ID', 'SEGMENT', 'CLM_FROM_DT', 'CLM_THRU_DT', 'PRVDR_NUM', 'CLM_PMT_AMT', 'NCH_PRMRY_PYR_CLM_PD_AMT', 'AT_PHYSN_NPI', 'OP_PHYSN_NPI', 'OT_PHYSN_NPI', 'NCH_BENE_BLOOD_DDCTBL_LBLTY_AM', 'ICD9_DGNS_CD_1', 'ICD9_DGNS_CD_2', 'ICD9_DGNS_CD_3', 'ICD9_DGNS_CD_4', 'ICD9_DGNS_CD_5', 'ICD9_DGNS_CD_6', 'ICD9_DGNS_CD_7', 'ICD9_DGNS_CD_8', 'ICD9_DGNS_CD_9', 'ICD9_DGNS_CD_10', 'ICD9_PRCDR_CD_1', 'ICD9_PRCDR_CD_2', 'ICD9_PRCDR_CD_3', 'ICD9_PRCDR_CD_4', 'ICD9_PRCDR_CD_5', 'ICD9_PRCDR_CD_6', 'NCH_BENE_PTB_DDCTBL_AMT', 'NCH_BENE_PTB_COINSRNC_AMT', 'ADMTNG_ICD9_DGNS_CD', 'HCPCS_CD_1', 'HCPCS_CD_2', 'HCPCS_CD_3', 'HCPCS_CD_4', 'HCPCS_CD_5', 'HCPCS_CD_6', 'HCPCS_CD_7', 'HCPCS_CD_8', 'HCPCS_CD_9', 'HCPCS_CD_10', 'HCPCS_CD_11', 'HCPCS_CD_12', 'HCPCS_CD_13', 'HCPCS_CD_14', 'HCPCS_CD_15', 'HCPCS_CD_16', 'HCPCS_CD_17', 'HCPCS_CD_18', 'HCPCS_CD_19', 'HCPCS_CD_20', 'HCPCS_CD_21', 'HCPCS_CD_22', 'HCPCS_CD_23', 'HCPCS_CD_24', 'HCPCS_CD_25', 'HCPCS_CD_26', 'HCPCS_CD_27', 'HCPCS_CD_28', 'HCPCS_CD_29', 'HCPCS_CD_30', 'HCPCS_CD_31', 'HCPCS_CD_32', 'HCPCS_CD_33', 'HCPCS_CD_34', 'HCPCS_CD_35', 'HCPCS_CD_36', 'HCPCS_CD_37', 'HCPCS_CD_38', 'HCPCS_CD_39', 'HCPCS_CD_40', 'HCPCS_CD_41', 'HCPCS_CD_42', 'HCPCS_CD_43', 'HCPCS_CD_44', 'HCPCS_CD_45']

In [12]:
print(otp['CLM_FROM_DT'].dtype)
print(otp['CLM_FROM_DT'].head())

float64
0    20080904.0
1    20090602.0
2    20090623.0
3    20091011.0
4    20080712.0
Name: CLM_FROM_DT, dtype: float64

In [13]:
otp = otp.dropna(subset=['CLM_FROM_DT'])

otp['CLM_FROM_DT'] = pd.to_datetime(
    otp['CLM_FROM_DT'].astype(int).astype(str),
    format='%Y%m%d'
)

print(otp['CLM_FROM_DT'].dtype)
print(otp['CLM_FROM_DT'].head())
print(f"Rows after dropping null dates: {otp.shape[0]}")

datetime64[ns]
0   2008-09-04
1   2009-06-02
2   2009-06-23
3   2009-10-11
4   2008-07-12
Name: CLM_FROM_DT, dtype: datetime64[ns]
Rows after dropping null dates: 779537

In [14]:
#filtering to 2010 claims only
otp_2010 = otp[otp['CLM_FROM_DT'].dt.year == 2010]

#filtering to cohort members only
otp_2010_cohort = otp_2010[otp_2010['DESYNPUF_ID'].isin(common_ids)]

#finding members with at least one claim
mem_with_claims_2010 = set(otp_2010_cohort['DESYNPUF_ID'].unique())

#building my label in the filtered_bene_2010 for dienganged members.
filtered_bene_2010['DISENGAGED'] = filtered_bene_2010['DESYNPUF_ID'].isin(mem_with_claims_2010)
filtered_bene_2010['DISENGAGED'] = filtered_bene_2010['DISENGAGED'].apply(lambda x: 0 if x else 1)

print(filtered_bene_2010['DISENGAGED'].value_counts())
print(f"\nDisengagement rate: {filtered_bene_2010['DISENGAGED'].mean()*100:.2f}%")

1    58084
0    54670
Name: DISENGAGED, dtype: int64

Disengagement rate: 51.51%

In [15]:
#overall data health
print(f"Total Cohort size: {len(filtered_bene_2010)}")
print(f"Engaged(0): {(filtered_bene_2010['DISENGAGED']==0).sum()}")
print(f"Disengaged(1): {(filtered_bene_2010['DISENGAGED']==1).sum()}")
print(f"Unique members with claims in 2010: {len(mem_with_claims_2010)}")
print(f"Unique memebers in out_patient 2010: {otp['DESYNPUF_ID'].nunique()}")

Total Cohort size: 112754
Engaged(0): 54670
Disengaged(1): 58084
Unique members with claims in 2010: 54670
Unique memebers in out_patient 2010: 85238


** THE MODEL ACCOUNTS FOR LONG-TERM MEMBERS PRESENT IN ALL THREE YEARS, 2008,2009, AND 2010. TO ACCOUNT FOR NEWLY JOINED MEMBERS FROM 2009 AND 2010, WE REQUIRE A NEW MODEL.

In [16]:
print(bene_2008.head())
print(bene_2009.head())
print(bene_2010.head())

        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             0             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            2
2                       12                        12  ...            2
3                        0                         0  ...            2
4                       12                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0          0.0        0.0        0.0         50.0       10.0        0.0
1          0.0        0.0        0.0          0.0        0.0        0.0
2          0.0        0.0        0.0          0.0        0.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         30.0       40.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0           0.0         0.0         0.0
1         700.0       240.0         0.0
2           0.0         0.0         0.0
3           0.0         0.0         0.0
4         220.0        80.0         0.0

[5 rows x 32 columns]
        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             0             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            1
2                       12                        12  ...            2
3                       12                        12  ...            2
4                       12                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0          0.0        0.0        0.0          0.0        0.0        0.0
1      36000.0     3204.0        0.0         60.0       70.0        0.0
2          0.0        0.0        0.0         30.0       50.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         90.0       40.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0         100.0        20.0         0.0
1        1350.0       530.0       100.0
2          20.0         0.0         0.0
3          90.0        10.0         0.0
4         410.0       140.0         0.0

[5 rows x 32 columns]
        DESYNPUF_ID  BENE_BIRTH_DT  BENE_DEATH_DT  BENE_SEX_IDENT_CD  \
0  00013D2EFD8E45D1       19230501            NaN                  1
1  00016F745862898F       19430101            NaN                  1
2  0001FDD721E223DC       19360901            NaN                  2
3  00021CA6FF03E670       19410601            NaN                  1
4  00024B3D2352D2D0       19360801            NaN                  1

   BENE_RACE_CD BENE_ESRD_IND  SP_STATE_CODE  BENE_COUNTY_CD  \
0             1             0             26             950
1             1             Y             39             230
2             1             0             39             280
3             5             0              6             290
4             1             0             52             590

   BENE_HI_CVRAGE_TOT_MONS  BENE_SMI_CVRAGE_TOT_MONS  ...  SP_STRKETIA  \
0                       12                        12  ...            2
1                       12                        12  ...            2
2                       12                        12  ...            2
3                       12                        12  ...            2
4                        9                        12  ...            2

   MEDREIMB_IP  BENRES_IP  PPPYMT_IP  MEDREIMB_OP  BENRES_OP  PPPYMT_OP  \
0       4000.0     1100.0        0.0          0.0        0.0        0.0
1      16000.0     1100.0        0.0          0.0        0.0        0.0
2          0.0        0.0        0.0          0.0        0.0        0.0
3          0.0        0.0        0.0          0.0        0.0        0.0
4          0.0        0.0        0.0         40.0        0.0        0.0

   MEDREIMB_CAR  BENRES_CAR  PPPYMT_CAR
0          90.0        30.0         0.0
1         930.0       150.0         0.0
2           0.0         0.0         0.0
3           0.0         0.0         0.0
4         590.0        60.0         0.0

[5 rows x 32 columns]

In [17]:
bene_2008.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,0,0,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,30.0,40.0,0.0,220.0,80.0,0.0

In [18]:
bene_2009.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,100.0,20.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,1,36000.0,3204.0,0.0,60.0,70.0,0.0,1350.0,530.0,100.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,30.0,50.0,0.0,20.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,90.0,10.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,90.0,40.0,0.0,410.0,140.0,0.0



NEXT STEP IS FEATURE ENGINEERING: FORM THE COLUMN VALUES OF bene_2008, bene_2009, bene_2010, I SEE 5 FEATURE CATEGORIES. 
1. Demographic        - age, sex, race
2. Geographic         - state, county
3. Coverage           - plan months, HMO months
4. Utilization        - IP/OP/CAR reimbursement amounts
5. Chronic Disease    - SP_ condition flags

LET'S HOW TO GO ABOUT FROM THERE!

In [19]:
SP_cols=[col for col in filtered_bene_2009.columns if col.startswith('SP_') and col not in ['SP_STATE_CODE']]
print(SP_cols)

['SP_ALZHDMTA', 'SP_CHF', 'SP_CHRNKIDN', 'SP_CNCR', 'SP_COPD', 'SP_DEPRESSN', 'SP_DIABETES', 'SP_ISCHMCHT', 'SP_OSTEOPRS', 'SP_RA_OA', 'SP_STRKETIA']

In [20]:
chronic_features = filtered_bene_2009[['DESYNPUF_ID'] + SP_cols].copy()

In [21]:
chronic_features['chronic_burden']=chronic_features[SP_cols].sum(axis=1)
print(chronic_features['chronic_burden'].describe())

count    112754.000000
mean         19.424411
std           2.519207
min          11.000000
25%          18.000000
50%          20.000000
75%          22.000000
max          22.000000
Name: chronic_burden, dtype: float64

In [22]:
print(filtered_bene_2009[SP_cols].head(10))
print(filtered_bene_2009[SP_cols].describe())

   SP_ALZHDMTA  SP_CHF  SP_CHRNKIDN  SP_CNCR  SP_COPD  SP_DEPRESSN  \
0            2       2            2        2        2            2
1            1       2            1        2        2            1
2            2       2            2        2        2            2
3            2       2            2        2        2            2
4            1       2            2        2        2            2
5            2       2            2        2        2            2
6            1       1            2        2        2            2
7            2       2            2        2        1            2
8            2       2            2        2        2            2
9            2       2            2        2        2            2

   SP_DIABETES  SP_ISCHMCHT  SP_OSTEOPRS  SP_RA_OA  SP_STRKETIA
0            2            2            2         2            2
1            1            1            2         1            1
2            2            2            2         2            2
3            2            1            2         2            2
4            2            1            2         2            2
5            2            2            2         2            2
6            1            1            1         1            2
7            1            2            2         2            2
8            2            2            2         2            2
9            2            2            2         2            2
         SP_ALZHDMTA         SP_CHF    SP_CHRNKIDN        SP_CNCR  \
count  112754.000000  112754.000000  112754.000000  112754.000000
mean        1.769489       1.655835       1.792992       1.918593
std         0.421162       0.475097       0.405163       0.273461
min         1.000000       1.000000       1.000000       1.000000
25%         2.000000       1.000000       2.000000       2.000000
50%         2.000000       2.000000       2.000000       2.000000
75%         2.000000       2.000000       2.000000       2.000000
max         2.000000       2.000000       2.000000       2.000000

             SP_COPD    SP_DEPRESSN    SP_DIABETES    SP_ISCHMCHT  \
count  112754.000000  112754.000000  112754.000000  112754.000000
mean        1.843935       1.754767       1.583793       1.523698
std         0.362919       0.430227       0.492931       0.499440
min         1.000000       1.000000       1.000000       1.000000
25%         2.000000       2.000000       1.000000       1.000000
50%         2.000000       2.000000       2.000000       2.000000
75%         2.000000       2.000000       2.000000       2.000000
max         2.000000       2.000000       2.000000       2.000000

         SP_OSTEOPRS       SP_RA_OA    SP_STRKETIA
count  112754.000000  112754.000000  112754.000000
mean        1.808628       1.825408       1.947275
std         0.393383       0.379620       0.223486
min         1.000000       1.000000       1.000000
25%         2.000000       2.000000       2.000000
50%         2.000000       2.000000       2.000000
75%         2.000000       2.000000       2.000000
max         2.000000       2.000000       2.000000

In [23]:
chronic_features[SP_cols] = chronic_features[SP_cols].replace({1: 1, 2: 0})

In [24]:
chronic_features.head()
chronic_features['chronic_burden']=chronic_features[SP_cols].sum(axis=1)
print(chronic_features['chronic_burden'].describe())

count    112754.000000
mean          2.575589
std           2.519207
min           0.000000
25%           0.000000
50%           2.000000
75%           4.000000
max          11.000000
Name: chronic_burden, dtype: float64

In [25]:
chronic_features.head()

,DESYNPUF_ID,SP_ALZHDMTA,SP_CHF,SP_CHRNKIDN,SP_CNCR,SP_COPD,SP_DEPRESSN,SP_DIABETES,SP_ISCHMCHT,SP_OSTEOPRS,SP_RA_OA,SP_STRKETIA,chronic_burden
0,00013D2EFD8E45D1,0,0,0,0,0,0,0,0,0,0,0,0
1,00016F745862898F,1,0,1,0,0,1,1,1,0,1,1,7
2,0001FDD721E223DC,0,0,0,0,0,0,0,0,0,0,0,0
3,00021CA6FF03E670,0,0,0,0,0,0,0,1,0,0,0,1
4,00024B3D2352D2D0,1,0,0,0,0,0,0,1,0,0,0,2

In [26]:
chronic_features.drop(columns="Total_chronic_count")

KeyError: "['Total_chronic_count'] not found in axis"

In [28]:
# Get 2008 chronic burden
chronic_2008 = filtered_bene_2008[['DESYNPUF_ID'] + SP_cols].copy()
chronic_2008[SP_cols] = chronic_2008[SP_cols].replace({1: 1, 2: 0})
chronic_2008['chronic_burden_2008'] = chronic_2008[SP_cols].sum(axis=1)

# Merge and calculate trend
chronic_features = chronic_features.merge(
    chronic_2008[['DESYNPUF_ID', 'chronic_burden_2008']], 
    on='DESYNPUF_ID'
)
chronic_features['chronic_burden_trend'] = chronic_features['chronic_burden'] - chronic_features['chronic_burden_2008']

print(chronic_features['chronic_burden_trend'].describe())
print(chronic_features.head())

count    112754.000000
mean          0.354728
std           1.712446
min          -9.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           9.000000
Name: chronic_burden_trend, dtype: float64
        DESYNPUF_ID  SP_ALZHDMTA  SP_CHF  SP_CHRNKIDN  SP_CNCR  SP_COPD  \
0  00013D2EFD8E45D1            0       0            0        0        0
1  00016F745862898F            1       0            1        0        0
2  0001FDD721E223DC            0       0            0        0        0
3  00021CA6FF03E670            0       0            0        0        0
4  00024B3D2352D2D0            1       0            0        0        0

   SP_DEPRESSN  SP_DIABETES  SP_ISCHMCHT  SP_OSTEOPRS  SP_RA_OA  SP_STRKETIA  \
0            0            0            0            0         0            0
1            1            1            1            0         1            1
2            0            0            0            0         0            0
3            0            0            1            0         0            0
4            0            0            1            0         0            0

   chronic_burden  chronic_burden_2008  chronic_burden_trend
0               0                    0                     0
1               7                    0                     7
2               0                    0                     0
3               1                    0                     1
4               2                    1                     1

In [29]:
print(chronic_features['chronic_burden_trend'].describe())
print(chronic_features.head())

count    112754.000000
mean          0.354728
std           1.712446
min          -9.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           9.000000
Name: chronic_burden_trend, dtype: float64
        DESYNPUF_ID  SP_ALZHDMTA  SP_CHF  SP_CHRNKIDN  SP_CNCR  SP_COPD  \
0  00013D2EFD8E45D1            0       0            0        0        0
1  00016F745862898F            1       0            1        0        0
2  0001FDD721E223DC            0       0            0        0        0
3  00021CA6FF03E670            0       0            0        0        0
4  00024B3D2352D2D0            1       0            0        0        0

   SP_DEPRESSN  SP_DIABETES  SP_ISCHMCHT  SP_OSTEOPRS  SP_RA_OA  SP_STRKETIA  \
0            0            0            0            0         0            0
1            1            1            1            0         1            1
2            0            0            0            0         0            0
3            0            0            1            0         0            0
4            0            0            1            0         0            0

   chronic_burden  chronic_burden_2008  chronic_burden_trend
0               0                    0                     0
1               7                    0                     7
2               0                    0                     0
3               1                    0                     1
4               2                    1                     1



UTILIZATION FEATURES

In [30]:
filtered_bene_2009.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,100.0,20.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,1,36000.0,3204.0,0.0,60.0,70.0,0.0,1350.0,530.0,100.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,30.0,50.0,0.0,20.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,90.0,10.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,90.0,40.0,0.0,410.0,140.0,0.0

In [31]:
util_features = filtered_bene_2009[["DESYNPUF_ID", "MEDREIMB_IP", "MEDREIMB_OP", "MEDREIMB_CAR"]].copy()

In [32]:
util_2008 = filtered_bene_2008[["DESYNPUF_ID", "MEDREIMB_IP", "MEDREIMB_OP", "MEDREIMB_CAR"]].copy()

util_2008 = util_2008.rename(
    columns={"MEDREIMB_IP":"MEDREIMB_IP_2008", "MEDREIMB_OP":"MEDREIMB_OP_2008", "MEDREIMB_CAR":"MEDREIMB_CAR_2008"}
)

In [33]:
util_features=util_features.merge(util_2008[["DESYNPUF_ID", "MEDREIMB_IP_2008", "MEDREIMB_OP_2008", "MEDREIMB_CAR_2008"]], on='DESYNPUF_ID')

In [34]:
util_features.head()

,DESYNPUF_ID,MEDREIMB_IP,MEDREIMB_OP,MEDREIMB_CAR,MEDREIMB_IP_2008,MEDREIMB_OP_2008,MEDREIMB_CAR_2008
0,00013D2EFD8E45D1,0.0,0.0,100.0,0.0,50.0,0.0
1,00016F745862898F,36000.0,60.0,1350.0,0.0,0.0,700.0
2,0001FDD721E223DC,0.0,30.0,20.0,0.0,0.0,0.0
3,00021CA6FF03E670,0.0,0.0,90.0,0.0,0.0,0.0
4,00024B3D2352D2D0,0.0,90.0,410.0,0.0,30.0,220.0

In [35]:
util_features["Total_MEDREIMB_IP"]=util_features["MEDREIMB_IP"]+util_features["MEDREIMB_IP_2008"]

In [36]:
util_features["Total_MEDREIMB_OP"]=util_features["MEDREIMB_OP"]+util_features["MEDREIMB_OP_2008"]

In [37]:
#util_features["Total_MEDREIMB_CAR"]=util_features["MEDREIMB_CAR"]+util_features["MEDREIMB_CAR_2008"]
util_features["Total_MEDREIMB_CAR"]

KeyError: 'Total_MEDREIMB_CAR'

In [38]:
util_features["Avg_MEDREIMB_IP"]=util_features[["MEDREIMB_IP", "MEDREIMB_IP_2008"]].mean(axis=1)
util_features["Avg_MEDREIMB_OP"]=util_features[["MEDREIMB_OP", "MEDREIMB_OP_2008"]].mean(axis=1)
util_features["Avg_MEDREIMB_CAR"]=util_features[["MEDREIMB_CAR", "MEDREIMB_CAR_2008"]].mean(axis=1)

In [39]:
util_features["MEDREIMB_IP_trend"]=util_features["MEDREIMB_IP"] - util_features["MEDREIMB_IP_2008"]
util_features["MEDREIMB_OP_trend"]=util_features["MEDREIMB_OP"] - util_features["MEDREIMB_OP_2008"]
util_features["MEDREIMB_CAR_trend"]=util_features["MEDREIMB_CAR"] - util_features["MEDREIMB_CAR_2008"]

In [40]:
util_features.head()

,DESYNPUF_ID,MEDREIMB_IP,MEDREIMB_OP,MEDREIMB_CAR,MEDREIMB_IP_2008,MEDREIMB_OP_2008,MEDREIMB_CAR_2008,Total_MEDREIMB_IP,Total_MEDREIMB_OP,Avg_MEDREIMB_IP,Avg_MEDREIMB_OP,Avg_MEDREIMB_CAR,MEDREIMB_IP_trend,MEDREIMB_OP_trend,MEDREIMB_CAR_trend
0,00013D2EFD8E45D1,0.0,0.0,100.0,0.0,50.0,0.0,0.0,50.0,0.0,25.0,50.0,0.0,-50.0,100.0
1,00016F745862898F,36000.0,60.0,1350.0,0.0,0.0,700.0,36000.0,60.0,18000.0,30.0,1025.0,36000.0,60.0,650.0
2,0001FDD721E223DC,0.0,30.0,20.0,0.0,0.0,0.0,0.0,30.0,0.0,15.0,10.0,0.0,30.0,20.0
3,00021CA6FF03E670,0.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,0.0,0.0,90.0
4,00024B3D2352D2D0,0.0,90.0,410.0,0.0,30.0,220.0,0.0,120.0,0.0,60.0,315.0,0.0,60.0,190.0

NOW I WILL BE BUILDING THE DEMOGRAPHICS FEATURE SET

In [ ]:
bene_2009.head()

In [42]:
bene_2009["BENE_BIRTH_DT"] = pd.to_datetime(
    bene_2009["BENE_BIRTH_DT"],
    format="%Y%m%d"
)

age_df = bene_2009[["DESYNPUF_ID", "BENE_BIRTH_DT"]].copy()
age_df["age"]= ( 
    pd.Timestamp("2009-12-31").year - age_df["BENE_BIRTH_DT"].dt.year
)
age_df.head()

        DESYNPUF_ID BENE_BIRTH_DT  age
0  00013D2EFD8E45D1    1923-05-01   86
1  00016F745862898F    1943-01-01   66
2  0001FDD721E223DC    1936-09-01   73
3  00021CA6FF03E670    1941-06-01   68
4  00024B3D2352D2D0    1936-08-01   73

In [43]:
demo_features = filtered_bene_2009[['DESYNPUF_ID', 'BENE_SEX_IDENT_CD', 
                                     'BENE_RACE_CD', 'SP_STATE_CODE',
                                     'BENE_COUNTY_CD']].copy()

# Add age
demo_features = demo_features.merge(age_df[['DESYNPUF_ID', 'age']], on='DESYNPUF_ID')

print(demo_features.shape)
print(demo_features.head())

(112754, 6)
        DESYNPUF_ID  BENE_SEX_IDENT_CD  BENE_RACE_CD  SP_STATE_CODE  \
0  00013D2EFD8E45D1                  1             1             26
1  00016F745862898F                  1             1             39
2  0001FDD721E223DC                  2             1             39
3  00021CA6FF03E670                  1             5              6
4  00024B3D2352D2D0                  1             1             52

   BENE_COUNTY_CD  age
0             950   86
1             230   66
2             280   73
3             290   68
4             590   73

****Feature Documentation:
- BENE_SEX_IDENT_CD: 1 = Male, 2 = Female
- BENE_RACE_CD: 1 = White, 2 = Black, 3 = Other, 
                4 = Asian, 5 = Hispanic, 6 = North American Native